### ISSUE TITLE
Not receive renbtc long after send btc and submit to ethereum

### ISSUE THREAD

**Issue by lyddream** [renproject/bridge#31]
btc tx hash:https://sochain.com/tx/BTC/012a3a99ff443233b3c394e120f7eb28f9415963dae3b589a4ba835d52179a6b
ethereum reciver address:0x60d582003E286fAcAA5ccBC45c846B6305939175

**Comment by TheAncientGoat** [comment]
Support team has reached out directly, closing this issue.
